{% set name = "oset" %}
{% set version = "0.1.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4c1fd7dec96eeff9d3260995a8e37f9f415d0bdb79975f57824e68716ac8f904" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - oset

about:
  home: https://gitorious.org/sleipnir/python-oset
  license: PSF
  license_family: PSF
  license_file: LICENSE.rst
  summary: Set that remembers original insertion order
  description: Set that remembers original insertion order.
    Implementation based on a doubly linked link and an internal dictionary. This design gives OrderedSet the same big-Oh running times as regular sets including O(1) adds, removes, and lookups as well as O(n) iteration.

extra:
  recipe-maintainers:
    - croth1
