travis:
  secure:
    BINSTAR_TOKEN: krRFmrRZG+kLPXD9IkZqvG5TFXRVsbP6XumTNhRMlcWLT3wJE50RIUslBZ7x21PE3Sal0DVfqar2PNdfGzWETIzHsSGf7EZpn6hRQ7m3Qfhc1J1tuEaeNyuASif7yqWsmnOfnWB2qGi8CbBH54HUCayJK3HaUIY8emcBY4YZ9gQ6OaKzSNHF2JBG5locfauHiAMz4GWeoTBhZGvLlOl4oGpr90qj7ls4Fbo1AmaJTP0mC5mpaK4IXgCnbxOAOpSSpy0IvI7LPTvrnjq8QAjA2RiVB5HTWiDsnU/0Z1i5O3ZDl7FWx2eP+037DCcw1K5n4Ukv5ApfCbeMQdZeCiYVcWbv8xGocPO4KXk/J5u4eFVMnW8YcZSjdDj/G8E8w9S+dnFeIXarPVWbFZxk8Dhzq3bdGrS6NEcfjKbjqw0BzjeTc97TGk8CwmnDI9x7OoNBoY6kTjjmU5Ma+HoDSWLOYLRPZVp+tCx/cSE7GvOBkTJS7Q6xj+OUuyKCg34MXPYBpdnrJoV5MNLzl/t69Yd1XKyo+Zmjbc0pCdoR84zYIgim1YNv+Uu0O9T45YTcuAMRUNnOlHzF6F5DsxAxBlvx2g30S0o4NB4y6ghbX44tCRH61JPwxckr5/4okukmluLp01oLyUlrjL1bRmul+4BfoN+LFgTdns0JioH4fOBUWds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
