travis:
  secure:
    BINSTAR_TOKEN: owRw7QfRAcjRT4Zu+VKW6TFEChFI0XpndMZVqTi5SvdfHQo2A/FZyDRYGJq5Ok7M/GgcjjBC9RRki6LX/o7GUDSfiT+S7eBCtn00XR2Syor3QT1jxhQVMY3QRKVGaCkBuoynF6x0fxiF1ctLEIIc8IVBRNNZKD/LS7fWzlppOsPNCW1X/CaTQefAfx8F422VXPDnCDJLVO1kH72747D9J4hhj/Tg3Ui7hdoMoNJAQA9zfmPy4hN/nBRnWOBE7883Sb9OeTVm25rujIYhSDN1a34liwUjwK12QJqac9J/CFLX0QVqb7oSgLDnOMwUfWSE/saegKYGUUJAzvT01W2i4ycHRrqH9k5tdLBrCdWoZIl0J6BwFjZr5gK+vAZNr75kvPnD0irtavHLbg0YxBdr1FNRwT5OUCnhAx/obDtYRPAwLHua02fSTs9CCZkluA5S5/+c2nc7qJwpvUxySHw2Gz5pXLXxPL7DhRJQBTUFBsSq4musiJmSEKTJ6gRp9yhR5g0rsqP+yld+VAARFXF7gPtK8iwAZFtezKsJXw4c5G/Ng4fC6RIXrOoQmVp16WlOmyyqQURED3Px8VdCEI3LQp9gdxeY8XZjbMNDrZMHCuLd20WHXV40yygjVpY+yJkYCEZXhodK0utMlqyKeq6bj2GUqplCfy94jFNvMlaA+fg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
